language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt
  - python setup.py install
script: clicheck -u tests/clicheck_test_suite.yaml run 
